### ISSUE TITLE
solve possible logjam vulnerability

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/JuiceMachineService#65]

**Comment by MBeuttler** [comment]
this issue involves all our virtual hosts:
- jmw
- jms
- core

**Comment by MBeuttler** [comment]
- Updated DHParams on JMS
```
openssl dhparam -out /etc/nginx/dhparams.pem 2048
ssl_dhparam /etc/nginx/dhparams.pem;
```
- JMW was not affected - as it already had 2048 dhparams
- CORE was not affected - as it is not reachable from public

![grafik](https://user-images.githubusercontent.com/3037112/40473524-ae00484c-5f3c-11e8-9e40-fe6e7294ffbb.png)
![grafik](https://user-images.githubusercontent.com/3037112/40473566-cdf87368-5f3c-11e8-80e0-16c57bdcbc05.png)
